# Generated by Django 5.0.6 on 2024-07-07 01:11

import apps.profile.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('username', models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2), django.core.validators.MaxLengthValidator(limit_value=25)])),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=2), django.core.validators.MaxLengthValidator(limit_value=50)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=2), django.core.validators.MaxLengthValidator(limit_value=50)])),
                ('contact', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=2), django.core.validators.MaxLengthValidator(limit_value=50)])),
                ('profile_image', models.ImageField(blank=True, upload_to='users/profiles/', validators=[apps.profile.validators.validate_image])),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_client', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='profile.users')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['id_client'],
            },
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id_admin', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='profile.users')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'ordering': ['id_admin'],
            },
        ),
    ]
